version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: taskmanager-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: syonet
      POSTGRES_PASSWORD: syonet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: taskmanager-backend
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/taskmanager
      QUARKUS_DATASOURCE_USERNAME: syonet
      QUARKUS_DATASOURCE_PASSWORD: syonet
    ports:
      - 8080:8080
    volumes:
      - ./backend/src/main/resources:/deployments/resources
    networks:
      - taskmanager-net

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: taskmanager-frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - taskmanager-net

volumes:
  postgres_data:

networks:
  taskmanager-net:
    driver: bridge